rails/coffeeshop_app/bootstrap_starter/config/routes.rb
Rails.application.routes.draw do
  root 'characters#index'
  
  get '/login'     => 'sessions#new'
  post '/login'    => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :users do
    resources :characters
  end

end

rails/coffeeshop_app/bootstrap_starter/app/models/character.rb
class Character < ActiveRecord::Base
	belongs_to :user
end

rails/coffeeshop_app/bootstrap_starter/app/models/user.rb
class User < ActiveRecord::Base
	has_many :characters, dependent: :destroy

	has_secure_password
end

rails/coffeeshop_app/bootstrap_starter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rails/coffeeshop_app/bootstrap_starter/app/controllers/characters_controller.rb
class CharactersController < ApplicationController
	before_action :set_character, only: [:show, :edit, :update, :destroy]

	# GET /characters
	def index
		if params[:user_id]
			@user = User.find(params[:user_id])
			@characters = @user.characters.all
		else
			@characters = Character.all
		end
	end

	# GET /characters/1
	def show
		@user = User.find(params[:user_id])
	end

	# GET /characters/new
	def new
		@user = User.find(params[:user_id])
		@character = Character.new
	end

	# GET /characters/1/edit
	def edit
		@user = User.find(params[:user_id])
	end

	# POST /characters
	def create
		@user = User.find(params[:user_id])
		@character = @user.characters.new(character_params)
		if @character.save
			redirect_to user_character_path(@user, @character)
		else
			render :new
		end
	end

	# PATCH/PUT /characters/1
	def update
		if @character.update(character_params)
			redirect_to user_character_path(@character.user, @character)
		else
			render :edit
		end
	end

	# DELETE /characters/1
	def destroy
		@user = User.find(session[:user_id])
		@character.destroy
		redirect_to user_characters_path(@user)
	end

private
	# Use callbacks to share common setup or constraints between actions.
	def set_character
		@character = Character.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def character_params
		params.require(:character).permit(:name, :age, :description, :active, :user_id)
	end
end

rails/coffeeshop_app/bootstrap_starter/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create	
		user = User.find_by(email: params[:login][:email])
		if user && user.authenticate(params[:login][:password])
			session[:user_id] = user.id.to_s
			redirect_to root_path
		else
			render :new
		end
	end

	def destroy
		session.delete(:user_id)
		redirect_to login_path
	end
end

rails/coffeeshop_app/bootstrap_starter/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy]

	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id.to_s
			redirect_to @user
		else
			render :new
		end
	end

	def show
	end

	def edit
	end

	def update
		if @user.update_attributes(user_params)
			redirect_to @user
		else
			render :edit
		end
	end

	def destroy
		@user.destroy
		redirect_to login_path
	end

private
	def set_user
		@user = User.find(params[:id])
	end

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end
end

rails/coffeeshop_app/bootstrap_starter/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/coffeeshop_app/bootstrap_starter/app/helpers/characters_helper.rb
module CharactersHelper
end

rails/coffeeshop_app/bootstrap_starter/app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end
end

rails/coffeeshop_app/bootstrap_starter/app/helpers/users_helper.rb
module UsersHelper
end

rails/coffeeshop_app/bootstrap_starter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BootstrapLessonPrep</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

	<% if current_user %>
		<ul class="nav nav-pills">
			<li><%= link_to current_user.name, user_path(current_user) %></li>
			<li role="presentation"><%= link_to 'My Characters', user_characters_path(current_user) %></li>
			<li role="presentation"><%= link_to 'Add a New Character',new_user_character_path(current_user) %></li>
			<li role="presentation"><%= link_to 'All Characters', root_path %></li>
			<li><%= link_to 'Log Out', logout_path, method: :delete %></li>
		</ul>
	<% else %>
		<%= link_to 'Log In', login_path, :class => 'btn btn-default' %>
		<%= link_to 'Sign Up', new_user_path, :class => 'btn btn-default' %>
	<% end %>


	<%= yield %>
	
</div>

</body>
</html>