bootstrap_starter/config/routes.rb
Rails.application.routes.draw do
  root 'characters#index'
  
  get '/login'     => 'sessions#new'
  post '/login'    => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :users do
    resources :characters
  end

end

bootstrap_starter/app/models/character.rb
class Character < ActiveRecord::Base
	belongs_to :user
end

bootstrap_starter/app/models/user.rb
class User < ActiveRecord::Base
	has_many :characters, dependent: :destroy

	has_secure_password
end

bootstrap_starter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

bootstrap_starter/app/controllers/characters_controller.rb
class CharactersController < ApplicationController
	before_action :set_character, only: [:show, :edit, :update, :destroy]

	# GET /characters
	def index
		if params[:user_id]
			@user = User.find(params[:user_id])
			@characters = @user.characters.all
		else
			@characters = Character.all
		end
	end

	# GET /characters/1
	def show
		@user = User.find(params[:user_id])
	end

	# GET /characters/new
	def new
		@user = User.find(params[:user_id])
		@character = Character.new
	end

	# GET /characters/1/edit
	def edit
		@user = User.find(params[:user_id])
	end

	# POST /characters
	def create
		@user = User.find(params[:user_id])
		@character = @user.characters.new(character_params)
		if @character.save
			redirect_to user_character_path(@user, @character)
		else
			render :new
		end
	end

	# PATCH/PUT /characters/1
	def update
		if @character.update(character_params)
			redirect_to user_character_path(@character.user, @character)
		else
			render :edit
		end
	end

	# DELETE /characters/1
	def destroy
		@user = User.find(session[:user_id])
		@character.destroy
		redirect_to user_characters_path(@user)
	end

private
	# Use callbacks to share common setup or constraints between actions.
	def set_character
		@character = Character.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def character_params
		params.require(:character).permit(:name, :age, :description, :active, :user_id)
	end
end

bootstrap_starter/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create	
		user = User.find_by(email: params[:login][:email])
		if user && user.authenticate(params[:login][:password])
			session[:user_id] = user.id.to_s
			redirect_to root_path
		else
			render :new
		end
	end

	def destroy
		session.delete(:user_id)
		redirect_to login_path
	end
end

bootstrap_starter/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy]

	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id.to_s
			redirect_to @user
		else
			render :new
		end
	end

	def show
	end

	def edit
	end

	def update
		if @user.update_attributes(user_params)
			redirect_to @user
		else
			render :edit
		end
	end

	def destroy
		@user.destroy
		redirect_to login_path
	end

private
	def set_user
		@user = User.find(params[:id])
	end

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end
end

bootstrap_starter/app/helpers/application_helper.rb
module ApplicationHelper
end

bootstrap_starter/app/helpers/characters_helper.rb
module CharactersHelper
end

bootstrap_starter/app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end
end

bootstrap_starter/app/helpers/users_helper.rb
module UsersHelper
end

bootstrap_starter/app/views/characters/_form.html.erb
<%= form_for [@user, @character] do |f| %>
  <% if @character.errors.any? %>
    <div id="error_explanation form-group">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% @character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div>
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

bootstrap_starter/app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form' %>

<%= link_to 'Show', user_character_path(@user, @character), :class => 'btn btn-success btn-xs active' %> |
<%= link_to 'Back', user_characters_path(@user), :class => 'btn btn-success btn-xs active' %>

bootstrap_starter/app/views/characters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Characters</h1>

<table class="table table-hover">
	<thead>
		<tr>
		<th>Name</th>
		<th>Age</th>
		<th>Description</th>
		<th>Active</th>
		<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @characters.each do |character| %>
			<tr>
			<td><%= character.name %></td>
			<td><%= character.age %></td>
			<td><%= character.description %></td>
			<td><%= character.active %></td>
			<td><%= link_to 'Show', user_character_path(character.user, character), :class => 'btn btn-success btn-xs active' %></td>
			<td><%= link_to 'Edit', edit_user_character_path(character.user, character), :class => 'btn btn-warning btn-xs active' %></td>
			<td><%= link_to 'Destroy', user_character_path(character.user, character), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-xs active' %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<br>

<%#= link_to 'New Character', new_user_character_path(current_user), :class => 'btn btn-primary btn-lg active' %>

bootstrap_starter/app/views/characters/new.html.erb
<h1>New Character</h1>

<%= render 'form' %>

<%= link_to 'Back', user_characters_path(@user), :class => 'btn btn-success btn-xs active' %>

bootstrap_starter/app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @character.age %>
</p>

<p>
  <strong>Description:</strong>
  <%= @character.description %>
</p>

<p>
  <strong>Active:</strong>
  <%= @character.active %>
</p>

<%= link_to 'Edit', edit_user_character_path(@user, @character), :class => 'btn btn-warning btn-xs active' %> |
<%= link_to 'Back', user_characters_path(@user), :class => 'btn btn-success btn-xs active' %>